// <auto-generated />
namespace CA1S00122306.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class leg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(leg));
        
        string IMigrationMetadata.Id
        {
            get { return "201403250417046_leg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
